### ISSUE TITLE
模型文件下载有问题

### ISSUE THREAD

**Issue by KingBoyAndGirl** [SkyworkAI/Vitron#2]
```sh
echo "prepared checkpoints for GLIGEN"
mkdir gligen
cd gligen
git clone https://huggingface.co/gligen/demo_ckpts_legacy
git clone https://huggingface.co/gligen/gligen-generation-text-box
git clone https://huggingface.co/gligen/gligen-generation-text-image-box
git clone https://huggingface.co/gligen/gligen-inpainting-text-box


cd ..
echo "prepared checkpoints for i2vgen-xl"
git clone https://huggingface.co/ali-vilab/i2vgen-xl



echo "prepared checkpoints for LanguageBind"
mkdir LanguageBind
cd LanguageBind
git clone https://huggingface.co/LanguageBind/LanguageBind_Video_merge
git clone https://huggingface.co/LanguageBind/LanguageBind_Image
git clone https://huggingface.co/LanguageBind/LanguageBind_Video

cd ..
echo "prepared checkpoints for OpenCLIP"
mkdir openai
cd openai
git clone https://huggingface.co/openai/clip-vit-large-patch14
git clone https://huggingface.co/openai/clip-vit-base-patch32

cd ..
echo "prepared checkpoints for stablevideo"
mkdir stablevideo
cd stablevideo

cd ..
echo "prepared checkpoints for Vitron-base"
mkdir Vitron-base
cd Vitron-base

cd ..
echo "prepared checkpoints for Vitron-lora"
mkdir Vitron-lora
cd Vitron-lora

cd ..
echo "prepared checkpoints for SEEM"
mkdir seem
cd seem

cd ..
echo "prepared checkpoints for Zeroscope"
mkdir zeroscope
cd zeroscope
git clone https://huggingface.co/cerspense/zeroscope_v2_576w
```

这是修改后的，但stablevideo、Vitron-base、Vitron-lora、seem文件还是缺失的，请作者百忙之中补充一下

**Comment by Bella1728** [comment]
same

**Comment by clannadcl** [comment]
> ```shell
> echo "prepared checkpoints for GLIGEN"
> mkdir gligen
> cd gligen
> git clone https://huggingface.co/gligen/demo_ckpts_legacy
> git clone https://huggingface.co/gligen/gligen-generation-text-box
> git clone https://huggingface.co/gligen/gligen-generation-text-image-box
> git clone https://huggingface.co/gligen/gligen-inpainting-text-box
> 
> 
> cd ..
> echo "prepared checkpoints for i2vgen-xl"
> git clone https://huggingface.co/ali-vilab/i2vgen-xl
> 
> 
> 
> echo "prepared checkpoints for LanguageBind"
> mkdir LanguageBind
> cd LanguageBind
> git clone https://huggingface.co/LanguageBind/LanguageBind_Video_merge
> git clone https://huggingface.co/LanguageBind/LanguageBind_Image
> git clone https://huggingface.co/LanguageBind/LanguageBind_Video
> 
> cd ..
> echo "prepared checkpoints for OpenCLIP"
> mkdir openai
> cd openai
> git clone https://huggingface.co/openai/clip-vit-large-patch14
> git clone https://huggingface.co/openai/clip-vit-base-patch32
> 
> cd ..
> echo "prepared checkpoints for stablevideo"
> mkdir stablevideo
> cd stablevideo
> 
> cd ..
> echo "prepared checkpoints for Vitron-base"
> mkdir Vitron-base
> cd Vitron-base
> 
> cd ..
> echo "prepared checkpoints for Vitron-lora"
> mkdir Vitron-lora
> cd Vitron-lora
> 
> cd ..
> echo "prepared checkpoints for SEEM"
> mkdir seem
> cd seem
> 
> cd ..
> echo "prepared checkpoints for Zeroscope"
> mkdir zeroscope
> cd zeroscope
> git clone https://huggingface.co/cerspense/zeroscope_v2_576w
> ```
> 
> 这是修改后的，但stablevideo、Vitron-base、Vitron-lora、seem文件还是缺失的，请作者百忙之中补充一下

请问解决了吗
